/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../public/model.glb -o Model.js 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { onAnimationsLoaded } = props;
  console.log('🎭 Model.jsx: Model component rendering');
  
  const group = React.useRef()
  
  console.log('📥 Model.jsx: Loading GLTF from /model.glb');
  const { scene, animations } = useGLTF('/model.glb')
  console.log('✅ Model.jsx: GLTF loaded successfully', { scene, animations });
  console.log('🎬 Model.jsx: Animation details:', animations.map(a => ({ name: a.name, duration: a.duration })));
  
  const clone = React.useMemo(() => {
    console.log('🔄 Model.jsx: Cloning scene');
    const cloned = SkeletonUtils.clone(scene);
    console.log('✅ Model.jsx: Scene cloned successfully');
    return cloned;
  }, [scene])
  
  const { nodes, materials } = useGraph(clone)
  console.log('📊 Model.jsx: Nodes and materials extracted', { 
    nodeCount: Object.keys(nodes).length, 
    materialCount: Object.keys(materials).length 
  });
  
  const { actions } = useAnimations(animations, group)
  console.log('🎬 Model.jsx: Animations setup', { 
    animationCount: animations.length,
    actionNames: Object.keys(actions),
    actions 
  });
  
  // Pass animation data to parent component after model loads
  React.useEffect(() => {
    if (onAnimationsLoaded && actions) {
      console.log('📤 Model.jsx: Model loaded, sending animation data to parent');
      onAnimationsLoaded(actions, animations);
    }
  }, [actions, animations, onAnimationsLoaded]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="node_Plane_(1)_-22118" position={[69.697, 0, 0]} scale={0.5} />
        <group name="node_Plane_(2)_-22864" position={[139.39, 0, 0]} scale={0.5} />
        <group name="node_Plane_(3)_-23936" position={[-139.39, 0, 0]} scale={0.5} />
        <group name="node_Plane_(4)_-23930" position={[-22.735, 0.012, 2.094]} scale={1.323} />
        <group name="node_Plane_(5)_-26960" position={[69.697, 0, -68.778]} scale={0.5} />
        <group name="node_Plane_(6)_-26940" position={[-69.697, 0, -68.778]} scale={0.5} />
        <group name="node_Plane_(7)_-26974" position={[0, 0, -68.778]} scale={0.5} />
        <group name="node_Plane_(8)_-26954" position={[139.39, 0, -68.778]} scale={0.5} />
        <group name="node_Plane_(9)_-26934" position={[-139.39, 0, -68.778]} scale={0.5} />
        <group name="node_Plane_(10)_-28220" position={[69.697, 0, 68.778]} scale={0.5} />
        <group name="node_Plane_(11)_-28240" position={[-69.697, 0, 68.778]} scale={0.5} />
        <group name="node_Plane_(12)_-28226" position={[139.39, 0, 68.778]} scale={0.5} />
        <group name="node_Plane_(13)_-28246" position={[-139.39, 0, 68.778]} scale={0.5} />
        <group name="node_Plane_(14)_-28206" position={[0, 0, 68.778]} scale={0.5} />
        <group name="node_Plane_-5828" scale={0.5} />
        <group name="root" position={[-101.457, 0.012, 2.094]} rotation={[-Math.PI / 2, 0, 0]} scale={2.646} />
        <group name="Sketchfab_model" position={[-101.457, 0.012, 2.094]} rotation={[-Math.PI / 2, 0, 0]} scale={2.646} />
        <group name="SM_colum_debri_1_0" position={[-114.41, 0.012, -20.054]} scale={2.646} />
        <group name="SM_colum_debri_2_1" position={[-80.302, -0.313, -21.957]} rotation={[-1.744, -0.138, -0.531]} scale={2.646} />
        <group name="SM_ruins_block_1_2" position={[-108.077, 0.012, 0.817]} scale={2.646} />
        <group name="SM_ruins_block_2_3" position={[-105.555, 0.012, 0.631]} scale={2.646} />
        <group name="SM_ruins_block_3_4" position={[-102.878, 0.012, 0.793]} scale={2.646} />
        <group name="SM_ruins_block_4_5" position={[-100.231, 0.012, 0.821]} scale={2.646} />
        <group name="SM_ruins_block_5_6" position={[-97.564, 0.012, 0.893]} scale={2.646} />
        <group name="SM_ruins_block_6_7" position={[-94.874, 0.012, 0.965]} scale={2.646} />
        <group name="SM_ruins_block_7_8" position={[-107.93, 0.012, 3.528]} scale={2.646} />
        <group name="SM_ruins_block_8_9" position={[-105.429, 0.012, 3.708]} scale={2.646} />
        <group name="SM_ruins_block_9_10" position={[-102.61, 0.012, 3.391]} scale={2.646} />
        <group name="SM_ruins_block_10_11" position={[-100.133, 0.012, 3.349]} scale={2.646} />
        <group name="SM_ruins_block_11_12" position={[-97.601, 0.012, 3.433]} rotation={[0, 1.571, 0]} scale={2.646} />
        <group name="SM_ruins_block_12_13" position={[-95.395, 0.012, -8.025]} scale={2.646} />
        <group name="SM_ruins_block_13_14" position={[-94.927, 0.012, 3.571]} scale={2.646} />
        <group name="node_Plane_(6)_-26940001" position={[50.706, 0, 50.734]} rotation={[0, 0.467, 0]} scale={0.5} />
        <group name="node_Plane_(9)_-26934001" position={[-11.539, 0, 82.08]} rotation={[0, 0.467, 0]} scale={0.5} />
        <group name="root001" position={[54.217, 0.012, 128.318]} rotation={[-Math.PI / 2, 0, 0.467]} scale={2.646} />
        <group name="Sketchfab_model001" position={[54.217, 0.012, 128.318]} rotation={[-Math.PI / 2, 0, 0.467]} scale={2.646} />
        <group name="SM_colum_debri_1_0001" position={[32.686, 0.012, 114.362]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_colum_debri_2_1001" position={[62.294, -0.313, 97.321]} rotation={[-1.664, -0.201, -0.062]} scale={2.646} />
        <group name="SM_ruins_block_1_2001" position={[47.73, 0.012, 130.154]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_2_3001" position={[49.899, 0.012, 128.854]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_3_4001" position={[52.363, 0.012, 127.794]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_4_5001" position={[54.74, 0.012, 126.629]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_5_6001" position={[57.154, 0.012, 125.494]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_6_7001" position={[59.589, 0.012, 124.347]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_7_8001" position={[49.081, 0.012, 132.51]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_8_9001" position={[51.396, 0.012, 131.545]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_9_10001" position={[53.771, 0.012, 129.994]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_10_11001" position={[55.964, 0.012, 128.843]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_11_12001" position={[58.263, 0.012, 127.779]} rotation={[-Math.PI, 1.104, -Math.PI]} scale={2.646} />
        <group name="SM_ruins_block_12_13001" position={[55.08, 0.012, 116.553]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="SM_ruins_block_13_14001" position={[60.714, 0.012, 126.7]} rotation={[0, 0.467, 0]} scale={2.646} />
        <group name="GS_type_F_clover" position={[-162.131, 1.203, -0.165]} rotation={[-Math.PI, 0.598, -Math.PI]} />
        <group name="Armature" position={[-62.243, 0, 25.226]} rotation={[Math.PI / 2, 0, 1.221]} scale={0.028}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="BezierCircle" geometry={nodes.BezierCircle.geometry} material={materials['Material.007']} skeleton={nodes.BezierCircle.skeleton} />
          <skinnedMesh name="BezierCircle002" geometry={nodes.BezierCircle002.geometry} material={materials['Material.007']} skeleton={nodes.BezierCircle002.skeleton} />
          <skinnedMesh name="BezierCircle003" geometry={nodes.BezierCircle003.geometry} material={materials['Material.007']} skeleton={nodes.BezierCircle003.skeleton} />
          <skinnedMesh name="NurbsPath002" geometry={nodes.NurbsPath002.geometry} material={materials['Material.007']} skeleton={nodes.NurbsPath002.skeleton} />
          <skinnedMesh name="Shirt" geometry={nodes.Shirt.geometry} material={materials['material_atlas_00001_1.001']} skeleton={nodes.Shirt.skeleton} morphTargetDictionary={nodes.Shirt.morphTargetDictionary} morphTargetInfluences={nodes.Shirt.morphTargetInfluences} />
        </group>
        <group name="node_Tree_-3298" position={[30.07, 4.13, 37.57]}>
          <mesh name="mesh_Tree_10986Tree" geometry={nodes.mesh_Tree_10986Tree.geometry} material={materials.Tree} />
          <mesh name="mesh_Tree_10986Tree_1" geometry={nodes.mesh_Tree_10986Tree_1.geometry} material={materials.Altar} />
          <mesh name="mesh_Tree_10986Tree_2" geometry={nodes.mesh_Tree_10986Tree_2.geometry} material={materials.Arches} />
          <mesh name="mesh_Tree_10986Tree_3" geometry={nodes.mesh_Tree_10986Tree_3.geometry} material={materials.Entrance} />
          <mesh name="mesh_Tree_10986Tree_4" geometry={nodes.mesh_Tree_10986Tree_4.geometry} material={materials.Platform} />
        </group>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.my_ruin_shader} position={[-119.053, 0.012, -20.054]} scale={2.646} />
        <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials.my_ruin_shader} position={[32.686, 0.012, 114.362]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.my_ruin_shader} position={[-80.302, -0.313, -27.153]} rotation={[-1.744, -0.138, -0.531]} scale={2.646} />
        <mesh name="Object_6001" geometry={nodes.Object_6001.geometry} material={materials.my_ruin_shader} position={[62.294, -0.313, 97.321]} rotation={[-1.664, -0.201, -0.062]} scale={2.646} />
        <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.my_ruin_shader} position={[-105.555, 0.012, 0.631]} scale={2.646} />
        <mesh name="Object_10001" geometry={nodes.Object_10001.geometry} material={materials.my_ruin_shader} position={[49.899, 0.012, 128.854]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.my_ruin_shader} position={[-100.231, 0.012, 0.821]} scale={2.646} />
        <mesh name="Object_14001" geometry={nodes.Object_14001.geometry} material={materials.my_ruin_shader} position={[54.74, 0.012, 126.629]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.my_ruin_shader} position={[-97.564, 0.012, 0.893]} scale={2.646} />
        <mesh name="Object_16001" geometry={nodes.Object_16001.geometry} material={materials.my_ruin_shader} position={[57.154, 0.012, 125.494]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.my_ruin_shader} position={[-94.874, 0.012, 0.965]} scale={2.646} />
        <mesh name="Object_18001" geometry={nodes.Object_18001.geometry} material={materials.my_ruin_shader} position={[59.589, 0.012, 124.347]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.my_ruin_shader} position={[-100.133, 0.012, 3.349]} scale={2.646} />
        <mesh name="Object_26001" geometry={nodes.Object_26001.geometry} material={materials.my_ruin_shader} position={[55.964, 0.012, 128.843]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.my_ruin_shader} position={[-94.927, 0.012, 3.571]} scale={2.646} />
        <mesh name="Object_32001" geometry={nodes.Object_32001.geometry} material={materials.my_ruin_shader} position={[60.714, 0.012, 126.7]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials.my_ruin_shader} position={[47.73, 0.012, 130.154]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_12001" geometry={nodes.Object_12001.geometry} material={materials.my_ruin_shader} position={[52.363, 0.012, 127.794]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_20001" geometry={nodes.Object_20001.geometry} material={materials.my_ruin_shader} position={[49.081, 0.012, 132.51]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_22001" geometry={nodes.Object_22001.geometry} material={materials.my_ruin_shader} position={[51.396, 0.012, 131.545]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_24001" geometry={nodes.Object_24001.geometry} material={materials.my_ruin_shader} position={[53.771, 0.012, 129.994]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="Object_28001" geometry={nodes.Object_28001.geometry} material={materials.my_ruin_shader} position={[58.263, 0.012, 127.779]} rotation={[-Math.PI, 1.104, -Math.PI]} scale={2.646} />
        <mesh name="Object_30001" geometry={nodes.Object_30001.geometry} material={materials.my_ruin_shader} position={[55.08, 0.012, 116.553]} rotation={[0, 0.467, 0]} scale={2.646} />
        <mesh name="QUARTZ1" geometry={nodes.QUARTZ1.geometry} material={materials['Material.005']} position={[-152.119, 4.12, -36.374]} scale={54.764} />
        <mesh name="QUARTZ3" geometry={nodes.QUARTZ3.geometry} material={materials['Material.003']} position={[-16.805, 13.215, 58.096]} scale={54.764} />
        <mesh name="QUARTZ4" geometry={nodes.QUARTZ4.geometry} material={materials['Material.004']} position={[-81.391, 4.698, -144.497]} scale={54.764} />
        <mesh name="QUARTZ5" geometry={nodes.QUARTZ5.geometry} material={materials['Material.006']} position={[-54.229, 9.201, -64.033]} scale={54.764} />
        <mesh name="QUARTZ7" geometry={nodes.QUARTZ7.geometry} material={materials['Material.002']} position={[-45.516, 0.42, 94.794]} scale={23.763} />
        <mesh name="Green_elka001_Plane001" geometry={nodes.Green_elka001_Plane001.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka002_Plane004" geometry={nodes.Green_elka002_Plane004.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka003_Plane005" geometry={nodes.Green_elka003_Plane005.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka004_Plane006" geometry={nodes.Green_elka004_Plane006.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka005_Plane007" geometry={nodes.Green_elka005_Plane007.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka006_Plane008" geometry={nodes.Green_elka006_Plane008.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka007_Plane009" geometry={nodes.Green_elka007_Plane009.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka008_Plane010" geometry={nodes.Green_elka008_Plane010.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka009_Plane011" geometry={nodes.Green_elka009_Plane011.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka012_Plane014" geometry={nodes.Green_elka012_Plane014.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka013_Plane015" geometry={nodes.Green_elka013_Plane015.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka014_Plane016" geometry={nodes.Green_elka014_Plane016.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka015_Plane017" geometry={nodes.Green_elka015_Plane017.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka016_Plane018" geometry={nodes.Green_elka016_Plane018.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka017_Plane019" geometry={nodes.Green_elka017_Plane019.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka018_Plane020" geometry={nodes.Green_elka018_Plane020.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka019_Plane021" geometry={nodes.Green_elka019_Plane021.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka020_Plane022" geometry={nodes.Green_elka020_Plane022.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka021_Plane023" geometry={nodes.Green_elka021_Plane023.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka022_Plane035" geometry={nodes.Green_elka022_Plane035.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka023_Plane036" geometry={nodes.Green_elka023_Plane036.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka024_Plane037" geometry={nodes.Green_elka024_Plane037.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka025_Plane038" geometry={nodes.Green_elka025_Plane038.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka026_Plane040" geometry={nodes.Green_elka026_Plane040.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka027_Plane041" geometry={nodes.Green_elka027_Plane041.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka028_Plane042" geometry={nodes.Green_elka028_Plane042.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka029_Plane044" geometry={nodes.Green_elka029_Plane044.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka030_Plane045" geometry={nodes.Green_elka030_Plane045.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka031_Plane046" geometry={nodes.Green_elka031_Plane046.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka032_Plane047" geometry={nodes.Green_elka032_Plane047.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka034_Plane049" geometry={nodes.Green_elka034_Plane049.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka035_Plane050" geometry={nodes.Green_elka035_Plane050.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka036_Plane051" geometry={nodes.Green_elka036_Plane051.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka037_Plane052" geometry={nodes.Green_elka037_Plane052.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka038_Plane053" geometry={nodes.Green_elka038_Plane053.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka039_Plane054" geometry={nodes.Green_elka039_Plane054.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka041_Plane056" geometry={nodes.Green_elka041_Plane056.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka042_Plane057" geometry={nodes.Green_elka042_Plane057.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka043_Plane058" geometry={nodes.Green_elka043_Plane058.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka044_Plane059" geometry={nodes.Green_elka044_Plane059.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka045_Plane060" geometry={nodes.Green_elka045_Plane060.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka047_Plane062" geometry={nodes.Green_elka047_Plane062.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka048_Plane063" geometry={nodes.Green_elka048_Plane063.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka049_Plane064" geometry={nodes.Green_elka049_Plane064.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka050_Plane065" geometry={nodes.Green_elka050_Plane065.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka052_Plane067" geometry={nodes.Green_elka052_Plane067.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka053_Plane068" geometry={nodes.Green_elka053_Plane068.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka054_Plane069" geometry={nodes.Green_elka054_Plane069.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka055_Plane070" geometry={nodes.Green_elka055_Plane070.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka056_Plane071" geometry={nodes.Green_elka056_Plane071.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka057_Plane072" geometry={nodes.Green_elka057_Plane072.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka058_Plane073" geometry={nodes.Green_elka058_Plane073.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka059_Plane074" geometry={nodes.Green_elka059_Plane074.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka060_Plane075" geometry={nodes.Green_elka060_Plane075.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka061_Plane076" geometry={nodes.Green_elka061_Plane076.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka062_Plane077" geometry={nodes.Green_elka062_Plane077.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka063_Plane078" geometry={nodes.Green_elka063_Plane078.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka064_Plane079" geometry={nodes.Green_elka064_Plane079.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka065_Plane080" geometry={nodes.Green_elka065_Plane080.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka066_Plane081" geometry={nodes.Green_elka066_Plane081.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka067_Plane082" geometry={nodes.Green_elka067_Plane082.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka068_Plane083" geometry={nodes.Green_elka068_Plane083.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka069_Plane084" geometry={nodes.Green_elka069_Plane084.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka070_Plane085" geometry={nodes.Green_elka070_Plane085.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka071_Plane086" geometry={nodes.Green_elka071_Plane086.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka072_Plane087" geometry={nodes.Green_elka072_Plane087.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka073_Plane088" geometry={nodes.Green_elka073_Plane088.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka074_Plane095" geometry={nodes.Green_elka074_Plane095.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka075_Plane096" geometry={nodes.Green_elka075_Plane096.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka076_Plane097" geometry={nodes.Green_elka076_Plane097.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka077_Plane098" geometry={nodes.Green_elka077_Plane098.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka078_Plane099" geometry={nodes.Green_elka078_Plane099.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka079_Plane100" geometry={nodes.Green_elka079_Plane100.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka080_Plane101" geometry={nodes.Green_elka080_Plane101.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka081_Plane102" geometry={nodes.Green_elka081_Plane102.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka082_Plane103" geometry={nodes.Green_elka082_Plane103.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka083_Plane104" geometry={nodes.Green_elka083_Plane104.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka084_Plane105" geometry={nodes.Green_elka084_Plane105.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka085_Plane106" geometry={nodes.Green_elka085_Plane106.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <group name="Green_elka087_Plane110" position={[-196.245, 8.716, 12.392]} rotation={[Math.PI / 2, 0, 0]} scale={5.67}>
          <mesh name="Green_elka087_Plane110_1" geometry={nodes.Green_elka087_Plane110_1.geometry} material={materials.Green_Elka} />
          <mesh name="Green_elka087_Plane110_2" geometry={nodes.Green_elka087_Plane110_2.geometry} material={materials['Wood_tree.001']} />
        </group>
        <mesh name="Green_elka088_Plane111" geometry={nodes.Green_elka088_Plane111.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka089_Plane112" geometry={nodes.Green_elka089_Plane112.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka090_Plane113" geometry={nodes.Green_elka090_Plane113.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka091_Plane114" geometry={nodes.Green_elka091_Plane114.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka092_Plane115" geometry={nodes.Green_elka092_Plane115.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka093_Plane116" geometry={nodes.Green_elka093_Plane116.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka094_Plane117" geometry={nodes.Green_elka094_Plane117.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka095_Plane118" geometry={nodes.Green_elka095_Plane118.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka096_Plane123" geometry={nodes.Green_elka096_Plane123.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka097_Plane124" geometry={nodes.Green_elka097_Plane124.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka098_Plane125" geometry={nodes.Green_elka098_Plane125.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka099_Plane126" geometry={nodes.Green_elka099_Plane126.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka100_Plane127" geometry={nodes.Green_elka100_Plane127.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <group name="Green_elka102_Plane129" position={[-85.953, 24.328, -74.242]} rotation={[Math.PI / 2, 0, 0]} scale={36.854}>
          <mesh name="Green_elka102_Plane129_1" geometry={nodes.Green_elka102_Plane129_1.geometry} material={materials.Green_Elka} />
          <mesh name="Green_elka102_Plane129_2" geometry={nodes.Green_elka102_Plane129_2.geometry} material={materials['Wood_tree.001']} />
        </group>
        <mesh name="Green_elka103_Plane131" geometry={nodes.Green_elka103_Plane131.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka104_Plane132" geometry={nodes.Green_elka104_Plane132.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka105_Plane133" geometry={nodes.Green_elka105_Plane133.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka106_Plane134" geometry={nodes.Green_elka106_Plane134.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka109_Plane137" geometry={nodes.Green_elka109_Plane137.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka110_Plane138" geometry={nodes.Green_elka110_Plane138.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka111_Plane139" geometry={nodes.Green_elka111_Plane139.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka112_Plane140" geometry={nodes.Green_elka112_Plane140.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka116_Plane144" geometry={nodes.Green_elka116_Plane144.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka117_Plane145" geometry={nodes.Green_elka117_Plane145.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka119_Plane147" geometry={nodes.Green_elka119_Plane147.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka120_Plane148" geometry={nodes.Green_elka120_Plane148.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka122_Plane150" geometry={nodes.Green_elka122_Plane150.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_elka_Plane" geometry={nodes.Green_elka_Plane.geometry} material={materials.Green_Elka} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna001_Plane024" geometry={nodes.Green_sosna001_Plane024.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna003_Plane026" geometry={nodes.Green_sosna003_Plane026.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna004_Plane027" geometry={nodes.Green_sosna004_Plane027.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna006_Plane029" geometry={nodes.Green_sosna006_Plane029.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna007_Plane030" geometry={nodes.Green_sosna007_Plane030.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna008_Plane031" geometry={nodes.Green_sosna008_Plane031.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna009_Plane032" geometry={nodes.Green_sosna009_Plane032.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna010_Plane033" geometry={nodes.Green_sosna010_Plane033.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna011_Plane034" geometry={nodes.Green_sosna011_Plane034.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna012_Plane039" geometry={nodes.Green_sosna012_Plane039.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna013_Plane043" geometry={nodes.Green_sosna013_Plane043.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna014_Plane089" geometry={nodes.Green_sosna014_Plane089.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna015_Plane090" geometry={nodes.Green_sosna015_Plane090.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna016_Plane091" geometry={nodes.Green_sosna016_Plane091.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna018_Plane093" geometry={nodes.Green_sosna018_Plane093.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna019_Plane094" geometry={nodes.Green_sosna019_Plane094.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna020_Plane108" geometry={nodes.Green_sosna020_Plane108.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna021_Plane109" geometry={nodes.Green_sosna021_Plane109.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna022_Plane119" geometry={nodes.Green_sosna022_Plane119.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna024_Plane121" geometry={nodes.Green_sosna024_Plane121.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna025_Plane122" geometry={nodes.Green_sosna025_Plane122.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Green_sosna026_Plane130" geometry={nodes.Green_sosna026_Plane130.geometry} material={materials['Green_sosna.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka001_Cone000" geometry={nodes.Wood_elka001_Cone000.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka002_Cone003" geometry={nodes.Wood_elka002_Cone003.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka003_Cone004" geometry={nodes.Wood_elka003_Cone004.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka004_Cone005" geometry={nodes.Wood_elka004_Cone005.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka005_Cone006" geometry={nodes.Wood_elka005_Cone006.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka006_Cone007" geometry={nodes.Wood_elka006_Cone007.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka007_Cone008" geometry={nodes.Wood_elka007_Cone008.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka008_Cone009" geometry={nodes.Wood_elka008_Cone009.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka009_Cone010" geometry={nodes.Wood_elka009_Cone010.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka012_Cone013" geometry={nodes.Wood_elka012_Cone013.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka013_Cone014" geometry={nodes.Wood_elka013_Cone014.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka014_Cone015" geometry={nodes.Wood_elka014_Cone015.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka015_Cone016" geometry={nodes.Wood_elka015_Cone016.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka016_Cone017" geometry={nodes.Wood_elka016_Cone017.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka017_Cone018" geometry={nodes.Wood_elka017_Cone018.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka018_Cone019" geometry={nodes.Wood_elka018_Cone019.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka019_Cone020" geometry={nodes.Wood_elka019_Cone020.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka020_Cone021" geometry={nodes.Wood_elka020_Cone021.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka021_Cone022" geometry={nodes.Wood_elka021_Cone022.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka022_Cone034" geometry={nodes.Wood_elka022_Cone034.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka023_Cone035" geometry={nodes.Wood_elka023_Cone035.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka024_Cone036" geometry={nodes.Wood_elka024_Cone036.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka025_Cone037" geometry={nodes.Wood_elka025_Cone037.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka026_Cone039" geometry={nodes.Wood_elka026_Cone039.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka027_Cone040" geometry={nodes.Wood_elka027_Cone040.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka028_Cone041" geometry={nodes.Wood_elka028_Cone041.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka029_Cone043" geometry={nodes.Wood_elka029_Cone043.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka030_Cone044" geometry={nodes.Wood_elka030_Cone044.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka031_Cone045" geometry={nodes.Wood_elka031_Cone045.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka032_Cone046" geometry={nodes.Wood_elka032_Cone046.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka033_Cone047" geometry={nodes.Wood_elka033_Cone047.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka034_Cone048" geometry={nodes.Wood_elka034_Cone048.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka035_Cone049" geometry={nodes.Wood_elka035_Cone049.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka036_Cone050" geometry={nodes.Wood_elka036_Cone050.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka037_Cone051" geometry={nodes.Wood_elka037_Cone051.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka038_Cone052" geometry={nodes.Wood_elka038_Cone052.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka039_Cone053" geometry={nodes.Wood_elka039_Cone053.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka040_Cone054" geometry={nodes.Wood_elka040_Cone054.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka041_Cone055" geometry={nodes.Wood_elka041_Cone055.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka042_Cone056" geometry={nodes.Wood_elka042_Cone056.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka043_Cone057" geometry={nodes.Wood_elka043_Cone057.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka044_Cone058" geometry={nodes.Wood_elka044_Cone058.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka045_Cone059" geometry={nodes.Wood_elka045_Cone059.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka047_Cone061" geometry={nodes.Wood_elka047_Cone061.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka048_Cone062" geometry={nodes.Wood_elka048_Cone062.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka049_Cone063" geometry={nodes.Wood_elka049_Cone063.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka050_Cone064" geometry={nodes.Wood_elka050_Cone064.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka051_Cone065" geometry={nodes.Wood_elka051_Cone065.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka052_Cone066" geometry={nodes.Wood_elka052_Cone066.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka053_Cone067" geometry={nodes.Wood_elka053_Cone067.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka054_Cone068" geometry={nodes.Wood_elka054_Cone068.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka055_Cone069" geometry={nodes.Wood_elka055_Cone069.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka056_Cone070" geometry={nodes.Wood_elka056_Cone070.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka057_Cone071" geometry={nodes.Wood_elka057_Cone071.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka058_Cone072" geometry={nodes.Wood_elka058_Cone072.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka059_Cone073" geometry={nodes.Wood_elka059_Cone073.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka060_Cone074" geometry={nodes.Wood_elka060_Cone074.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka061_Cone075" geometry={nodes.Wood_elka061_Cone075.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka062_Cone076" geometry={nodes.Wood_elka062_Cone076.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka063_Cone077" geometry={nodes.Wood_elka063_Cone077.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka064_Cone078" geometry={nodes.Wood_elka064_Cone078.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka065_Cone079" geometry={nodes.Wood_elka065_Cone079.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka066_Cone080" geometry={nodes.Wood_elka066_Cone080.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka067_Cone081" geometry={nodes.Wood_elka067_Cone081.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka068_Cone082" geometry={nodes.Wood_elka068_Cone082.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka069_Cone083" geometry={nodes.Wood_elka069_Cone083.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka070_Cone084" geometry={nodes.Wood_elka070_Cone084.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka071_Cone085" geometry={nodes.Wood_elka071_Cone085.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka072_Cone086" geometry={nodes.Wood_elka072_Cone086.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka073_Cone087" geometry={nodes.Wood_elka073_Cone087.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka074_Cone094" geometry={nodes.Wood_elka074_Cone094.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka075_Cone095" geometry={nodes.Wood_elka075_Cone095.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka076_Cone096" geometry={nodes.Wood_elka076_Cone096.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka077_Cone097" geometry={nodes.Wood_elka077_Cone097.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka078_Cone098" geometry={nodes.Wood_elka078_Cone098.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka079_Cone099" geometry={nodes.Wood_elka079_Cone099.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka080_Cone100" geometry={nodes.Wood_elka080_Cone100.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka081_Cone101" geometry={nodes.Wood_elka081_Cone101.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka082_Cone102" geometry={nodes.Wood_elka082_Cone102.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka083_Cone103" geometry={nodes.Wood_elka083_Cone103.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka084_Cone104" geometry={nodes.Wood_elka084_Cone104.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka085_Cone105" geometry={nodes.Wood_elka085_Cone105.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka088_Cone110" geometry={nodes.Wood_elka088_Cone110.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka089_Cone111" geometry={nodes.Wood_elka089_Cone111.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka090_Cone112" geometry={nodes.Wood_elka090_Cone112.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka091_Cone113" geometry={nodes.Wood_elka091_Cone113.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka092_Cone114" geometry={nodes.Wood_elka092_Cone114.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka093_Cone115" geometry={nodes.Wood_elka093_Cone115.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka094_Cone116" geometry={nodes.Wood_elka094_Cone116.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka095_Cone117" geometry={nodes.Wood_elka095_Cone117.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka096_Cone122" geometry={nodes.Wood_elka096_Cone122.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka097_Cone123" geometry={nodes.Wood_elka097_Cone123.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka098_Cone124" geometry={nodes.Wood_elka098_Cone124.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka099_Cone125" geometry={nodes.Wood_elka099_Cone125.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka100_Cone126" geometry={nodes.Wood_elka100_Cone126.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka101_Cone127" geometry={nodes.Wood_elka101_Cone127.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka103_Cone130" geometry={nodes.Wood_elka103_Cone130.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka104_Cone131" geometry={nodes.Wood_elka104_Cone131.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka105_Cone132" geometry={nodes.Wood_elka105_Cone132.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka106_Cone133" geometry={nodes.Wood_elka106_Cone133.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka107_Cone134" geometry={nodes.Wood_elka107_Cone134.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka108_Cone135" geometry={nodes.Wood_elka108_Cone135.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka109_Cone136" geometry={nodes.Wood_elka109_Cone136.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka110_Cone137" geometry={nodes.Wood_elka110_Cone137.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka111_Cone138" geometry={nodes.Wood_elka111_Cone138.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka112_Cone139" geometry={nodes.Wood_elka112_Cone139.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka116_Cone143" geometry={nodes.Wood_elka116_Cone143.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka117_Cone144" geometry={nodes.Wood_elka117_Cone144.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka119_Cone146" geometry={nodes.Wood_elka119_Cone146.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka120_Cone147" geometry={nodes.Wood_elka120_Cone147.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka122_Cone149" geometry={nodes.Wood_elka122_Cone149.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_elka_Cone001" geometry={nodes.Wood_elka_Cone001.geometry} material={materials['Wood_tree.001']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna001_Cone023" geometry={nodes.Wood_sosna001_Cone023.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna002_Cone024" geometry={nodes.Wood_sosna002_Cone024.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna003_Cone025" geometry={nodes.Wood_sosna003_Cone025.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna004_Cone026" geometry={nodes.Wood_sosna004_Cone026.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna006_Cone028" geometry={nodes.Wood_sosna006_Cone028.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna007_Cone029" geometry={nodes.Wood_sosna007_Cone029.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna008_Cone030" geometry={nodes.Wood_sosna008_Cone030.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna009_Cone031" geometry={nodes.Wood_sosna009_Cone031.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna010_Cone032" geometry={nodes.Wood_sosna010_Cone032.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna011_Cone033" geometry={nodes.Wood_sosna011_Cone033.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna012_Cone038" geometry={nodes.Wood_sosna012_Cone038.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna013_Cone042" geometry={nodes.Wood_sosna013_Cone042.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna014_Cone088" geometry={nodes.Wood_sosna014_Cone088.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna015_Cone089" geometry={nodes.Wood_sosna015_Cone089.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna016_Cone090" geometry={nodes.Wood_sosna016_Cone090.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna017_Cone091" geometry={nodes.Wood_sosna017_Cone091.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna018_Cone092" geometry={nodes.Wood_sosna018_Cone092.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna019_Cone093" geometry={nodes.Wood_sosna019_Cone093.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna020_Cone107" geometry={nodes.Wood_sosna020_Cone107.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna021_Cone108" geometry={nodes.Wood_sosna021_Cone108.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna022_Cone118" geometry={nodes.Wood_sosna022_Cone118.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <group name="Wood_sosna023_Cone119" position={[80.814, 43.926, 201.485]} rotation={[Math.PI / 2, 0, 0]} scale={36.854}>
          <mesh name="Wood_sosna023_Cone119_1" geometry={nodes.Wood_sosna023_Cone119_1.geometry} material={materials['Green_sosna.001']} />
          <mesh name="Wood_sosna023_Cone119_2" geometry={nodes.Wood_sosna023_Cone119_2.geometry} material={materials['Wood_tree.002']} />
        </group>
        <mesh name="Wood_sosna024_Cone120" geometry={nodes.Wood_sosna024_Cone120.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna025_Cone121" geometry={nodes.Wood_sosna025_Cone121.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Wood_sosna026_Cone129" geometry={nodes.Wood_sosna026_Cone129.geometry} material={materials['Wood_tree.002']} position={[64.412, -0.077, -0.506]} rotation={[Math.PI / 2, 0, 0]} scale={36.854} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.001']} scale={243.612} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
